[mgr]
ratio = [1, 2, 2]
sort_by = "extension"
sort_dir_first = true
linemode = "size"
show_hidden = true


[preview]
wrap = "yes"
image_delay = 0
image_quality = 65
max_width = 3840
max_height = 2160
