[Colors]
accent=#bca6f7
background=#1e1e2e
background_fullscreen=#1e1e2e
folderview=#1e1e2e
folderview_topbar=#1e1e2e
icons=#cdd6f4
overlay=#11111b
overlay_text=#cdd6f4
scrollbar=#6c7086
text=#cdd6f4
tid=2
widget=#11111b
widget_border=#11111b
